# -*- coding: utf-8 -*-
"""VasuRebalancingTrainingClass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNE6KQ_jvLqQd7A45vRkDov_6_nkjnc1
"""

data_dir = "datasets"

import pandas as pd
import torch
import os
from shared_functions_datasets import batch_data

### assume we have filelistcsv loaded
FileListCSV = pd.read_csv("FileList.csv")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train_video_tensors = []
train_video_labels = []

training = FileListCSV[FileListCSV['Split'] == 'TRAIN']
training_positive_examples = training[training['EFBelow40'] == 1]
training_positive_examples = training_positive_examples.sample(frac=1.0, random_state=42)

training_negative_examples = training[training['EFBelow40'] == 0]
training_negative_examples = training_negative_examples.sample(frac=1.0, random_state=42)
training_negative_examples = training_negative_examples[:948]

training_rebalanced = pd.concat([training_positive_examples, training_negative_examples], axis = 0)
training_rebalanced = training_rebalanced.sample(frac=1.0, random_state=42)

training_rebalanced_files = training_rebalanced[training_rebalanced['Split'] == 'TRAIN']['FileName'].tolist()

batch_size = 20

### CHANGE FOR YOUR PURPOSES
location_of_videos = data_dir + '/' + 'train'

print(len(os.listdir(location_of_videos)))

### DESTINATION DIRECTORY FOR TENSOR BATCHES
folder_destination = "datasets" + '/' + 'train_batched_downsampled_rebalanced'

if not os.path.exists(folder_destination):
    # If the directory does not exist, create it using os.makedirs()
    os.makedirs(folder_destination)

### CALLING FUNCTION
train_videos_used_so_far = []
print("len(training_rebalanced_files) is: ", len(training_rebalanced_files))
batch_data(data_dir, 20, training_rebalanced_files, [], phase = 'train', rebalancing=True)