# -*- coding: utf-8 -*-
"""VasuDownsampleVideos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpKTgljdiT1nxTnjwCqsGrCK1dYCSdbz
"""

data_dir = "datasets"

import pandas as pd
import torch
from shared_functions_datasets import batch_data

### assume we have filelistcsv loaded
FileListCSV = pd.read_csv("FileList.csv")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train_files = FileListCSV[FileListCSV['Split'] == 'TRAIN']['FileName'].tolist()
validation_files = FileListCSV[FileListCSV['Split'] == 'VAL']['FileName'].tolist()
test_files = FileListCSV[FileListCSV['Split'] == 'TEST']['FileName'].tolist()

batch_data(data_dir, 20, train_files, [], phase='train')
batch_data(data_dir, 20, validation_files, [], phase='val')
batch_data(data_dir, 20, test_files, [], phase='test')